config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts do
    collection do
      get :search
    end

    member do
      post :like
      post :dislike
    end
  end

  resources :users, only: %w(new create) do
    collection do
      get :invites
    end
  end

  get  "/login",  to: "sessions#new",     as: :login
  post "/login",  to: "sessions#create"
  post "/logout", to: "sessions#destroy", as: :logout
end

app/models/invite.rb
class Invite
  REDIS_KEY = "invite_nonces"

  def self.generate(user)
    raise ArgumentError unless user
    new(user: user).token
  end

  def self.from_token(token)
    raise ArgumentError unless token
    new(token: token)
  end

  def initialize(user: nil, token: nil)
    @uid = user.id if user
    @user = user
    @token = token
  end

  def valid?
    user && user.admin? && !redeemed?
  end

  def token
    @token ||= generate_token
  end

  def redeem!
    redis.sadd(REDIS_KEY, nonce)
  end

  private

  def user
    @user ||= User.find(uid)
  end

  def uid
    @uid ||= parse_token["uid"]
  end

  def nonce
    @nonce ||= SecureRandom.hex(8)
  end

  def redeemed?
    redis.sismember(REDIS_KEY, nonce)
  end

  def redis
    Rails.application.config.redis
  end

  def generate_token
    message_encryptor.encrypt_and_sign(uid: uid, nonce: nonce)
  end

  def parse_token
    message_encryptor.decrypt_and_verify(token)
  end

  def message_encryptor
    @message_encryptor||= ActiveSupport::MessageEncryptor.new(
      Rails.application.config.crypto_key,
      'aes-256-cbc',
      serializer: JSON
    )
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :votes

  validates :name, presence: true
  validates :body, presence: true

  after_save :index

  def score
    votes.sum(:value)
  end

  def self.search(query)
    Rails.configuration.search_index.search query
  end

  private

  def index
    Rails.configuration.search_index.index(id, body)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :votes

  validates :login, uniqueness: true
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user, uniqueness: {scope: :post, message: 'can only vote once per post'}
  validates :value, inclusion: { in: [1, -1], message: 'can only vote +1/-1' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def login_as(user)
    @current_user = user
    session[:user_id] = user.id
  end

  def current_user
    return @current_user if defined? @current_user
    @current_user = User.find_by_id session[:user_id]
  end
  helper_method :current_user

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  def admin?
    logged_in? && current_user.admin?
  end
  helper_method :admin?

  def authenticated_only
    access_denied unless logged_in?
  end

  def anonymous_only
    access_denied if logged_in?
  end

  def admin_only
    access_denied unless admin?
  end

  def access_denied
    render(status: 401, text: "access denied")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :admin_only,         only: [:new, :create, :edit, :update]
  before_filter :authenticated_only, only: [:like, :dislike]

  def index
    @posts = Post.all
  end

  def search
    @posts = Post.search(params[:q])
  end

  def show
    @already_voted = logged_in? && this_post.votes.where(user: current_user).any?
  end

  def new
    @this_post = Post.new
  end

  def create
    @this_post = Post.new post_params
    if this_post.save
      flash.now[:error] = this_post.errors.full_messages.to_sentence
      render :new
    else
      redirect_to post_path(this_post)
    end
  end

  def edit
  end

  def update
    if this_post.update_attributes post_params
      redirect_to post_path(this_post)
    else
      flash[:error] = this_post.errors.full_messages.to_sentence
      redirect_to edit_post_path(this_post)
    end
  end

  def like
    vote +1
  end

  def dislike
    vote -1
  end

  private

  def vote(value)
    record = current_user.votes.new(post: this_post, value: value)
    if record.save
      render json: { error: "", votes: this_post.score, the_flag: ENV['THE_FLAG'] }
    else
      render json: { error: record.errors.full_messages.to_sentence, votes: this_post.score }
    end
  end

  def post_params
    params.require(:post).permit(:name, :body)
  end

  def this_post
    return @this_post if defined? @this_post
    @this_post = Post.find_by_id(params[:id].to_i)
  end
  helper_method :this_post
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :anonymous_only,     only: [:new, :create]
  before_filter :authenticated_only, only: [:destroy]

  def new
  end

  def create
    unless user = User.find_by_login(params[:login])
      flash[:error] = "Incorrect username or password"
      return render("new")
    end

    unless user.authenticate(params[:password])
      flash[:error] = "Incorrect username or password"
      return render("new")
    end

    login_as(user)
    redirect_to root_path
  end

  def destroy
    reset_session
    @current_user = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :invite_required, only: [:new, :create]
  before_filter :anonymous_only,  only: [:new, :create]
  before_filter :admin_only,      only: [:invites]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save && invite.redeem!
      login_as(@user)
      flash[:notice] = "You are now logged in as #{@user.login}"
      redirect_to "/"
    else
      flash.now[:error] = @user.errors.full_messages.to_sentence
      render "new"
    end
  end

  def invites
    urls = 10.times.map { new_user_url(invite: Invite.generate(current_user)) }
    render plain: urls.join("\n")
  end

  private

  def invite_required
    access_denied unless invite
    access_denied unless invite.valid?
  end

  def invite
    return @invite if defined? @invite
    @invite = Invite.from_token params[:invite]
  end
  helper_method :invite

  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <title>The blog.</title>
  </head>
  <body>
    <div class="header">
      <div class="header-right">
        <div class="current-user">
          <% if logged_in? %>
            Logged in as @<%= current_user.login %>.
            <%= link_to "Logout", logout_path, method: :post %>
          <% else %>
            <%= link_to "Login", login_path %>
          <% end %>
        </div>
        <%= form_tag search_posts_path, method: "get", class: "search" do %>
          <%= text_field_tag :q, params[:q] %>
          <%= submit_tag("Search") %>
        <% end %>
      </div>
      <%= link_to "The blog.", root_path, class: "headline" %>
    </div>
    <div class="content">
      <div class="error-flash"><%= flash[:error] %></div>
      <div class="notice-flash"><%= flash[:notice] %></div>
      <%= yield %>
    </div>
    <div class="footer">
      <a href="https://github.com/mastahyeti/the-blog">Fork The Blog on GitHub</a>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for this_post do |f| %>
  Name: <%= f.text_field :name %><br>
  Body: <%= f.text_area :body %><br>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
<ul>
  <% @posts.each do |post| %>
    <li class="post">
      <%= link_to post.name, post %> <%= link_to("(edit)", edit_post_path(post)) if admin? %>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/search.html.erb
<ul>
  <% @posts.each do |post| %>
    <li class="post">
      <%= link_to "Post #{post}", post_path(id: post) %>
    </li>
  <% end %>
</ul>

app/views/posts/show.html.erb
<h3 class="name"><%= this_post.name %></h3>
<div class="body">
  <%= this_post.body.html_safe %>
</div>
<div class="votes">
  Votes: <div class="vote-count"><%= this_post.score %></div>
  <% unless !logged_in? || @already_voted %>
  <div class="voting">
    <%= link_to "like", like_post_path(this_post), remote: true, method: :post, class: 'js-vote-button' %>
    <%= link_to "dislike", dislike_post_path(this_post), remote: true, method: :post, class: 'js-vote-button' %>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  login: <%= f.text_field :login %><br>
  password: <%= f.password_field :password %><br>
  password confirmation: <%= f.password_field :password_confirmation %><br>
  <%= hidden_field_tag :invite, invite.token %>
  <%= f.submit %>
<% end %>